### ISSUE TITLE
General Question Re Trickplay failure

### ISSUE THREAD

**Issue by p37307** [jellyfin/jellyfin-roku#101]
I noticed when videos are transcoding for Roku, trickplay is not working. Trickplay does work for videos that don't have to be transcoded. Is this a common issue?

I've searched and read https://github.com/1hitsong/viv/issues/14 and those solutions don't apply to me.

I do have a log I can share of a transcoded attempt where the Trickplay worked in the web but not on Roku transcoding. I checked various videos of different types that get transcoded, it seems that way across the board.

**Comment by 1hitsong** [comment]
> Is this a common issue?

No. In fact, this is the first I've heard of it. I just tested on 3 of my Rokus with a transcoded video, and they all worked.

In fact, when transcoding, the trickplay display is nicer because when transcoding Roku will generate the trickplay images itself in device and does the display of them in a way viv cannot.

**Direct Play**
![WIN_20241210_08_45_28_Pro](https://github.com/user-attachments/assets/fc52f6df-247a-430d-aa0e-8795e0600e28)

**Transcoding**
![WIN_20241210_08_46_08_Pro](https://github.com/user-attachments/assets/e8ea5e35-c65a-48b7-b270-443b7f7a0fba)

I'll poke around behind the scenes and see what I can find. There is code to not show the custom trickplay if the Roku trickplay shows. Perhaps I can improve that logic to know not only if the Roku trickplay component shows, but if it loaded any images.

**Comment by p37307** [comment]
> No. In fact, this is the first I've heard of it.

This is the first time I have noticed it, and I know it wasn't a noticeable issue before and pretty sure I've used trickplay forward for some of these shows.

**Comment by 1hitsong** [comment]
I've racked my brain on this, but there's nothing in code that would indicate why Roku wouldn't show its own trickplay images. The property I'm checking is only set if Roku finds images and the expectation is it will use them. 🤷 

You mentioned it used to work for you. This indicates the code I added to prevent both the custom trickplay display AND the Roku trickplay display from showing at the same time is working, but for some reason the Roku one isn't working.

Since I have no other levers to pull here, I've created a hidden setting that allows you to force display the custom trickplay images no matter what. This is a hidden setting because in all my testing this will cause both to show at the same time - one on top of the other.

https://github.com/user-attachments/assets/fe44b8e3-4dd3-40dc-b816-e2e7d35892a8

This new setting area is accessed by:

1. Go into settings - do not press any buttons. The following key press sequence must be the first keys pressed
2. Up
3. LEFT
4. REPLAY
5. REWIND
6. UP
7. LEFT
8. REPLAY
9. REWIND

There's a 5 second timer between each key press to press the next key. If the timer expires, you'll need to start again from the beginning.

**Comment by p37307** [comment]
> I've racked my brain on this, but there's nothing in code that would indicate why Roku wouldn't show its own trickplay images. The property I'm checking is only set if Roku finds images and the expectation is it will use them. 🤷

Sorry for the delay.

The trickplays started working after turning the secret option on, but any show that is transcoded now appears in a green box while the video plays in a small box in the upper left-hand side.

For videos that aren't transcoded, everything appears works fine. 

Image, tv on wall. Video playing. Green screen with a small box that contains the active video play. Trickplay showing below,
![image](https://github.com/user-attachments/assets/949207e9-e50c-458e-a8fd-500c2be7405c)

Image, tv on wall. Video playing. Green screen with a small box that contains the active video play. Video playing normally without any trickplay view
![image](https://github.com/user-attachments/assets/8f9ff372-78e7-4f05-bf4c-90b3742b0d36)

**Comment by 1hitsong** [comment]
1. Are you forcing transcode using the option, or is this a natural transcode happening?
2. Does it look the same in the production viv client?
3. Does it look the same in the Jellyfin client?

**Comment by p37307** [comment]
To clarify, it appears it is AVI's that are not playing trickplays. It also appears the green box issue is a fluke. See below.

> This is a hidden setting because in all my testing this will cause both to show at the same time - one on top of the other.

I never noticed two versions of trickplays on top of each other

> 1. Are you forcing transcode using the option, or is this a natural transcode happening?

The green screen above had to be forced for trickplay to work under the secret menu option. It appears the issue with the green box only occurred on one of my 4 rokus. The others, with the secret turned on, do not do the green box. That TV is a Roku Element TV. We can trash the greenscreen issue, I think. I think it is a corrupted file.

> 2. Does it look the same in the production viv client?

No, appears normal with and without forced transcoding but trickplays don't work.

> 3. Does it look the same in the Jellyfin client?

No, appears normal.

Excluding the green screen issue above as fluke, not related to VIV, Jellyfin, etc,  I did test several avis that have been in my library for years and the trickplay issue exists for them. 

I am including 3 different logs of the same video played via viv, viv dev (unforced transcoding, trickplay worked with secret turned on) and Jellyfin.
[FFmpeg.Transcode-viv dev.log](https://github.com/user-attachments/files/18275909/FFmpeg.Transcode-viv.dev.log)
[FFmpeg.Transcode-jellyfin.log](https://github.com/user-attachments/files/18275910/FFmpeg.Transcode-jellyfin.log)
[FFmpeg.Transcode-viv.log](https://github.com/user-attachments/files/18275911/FFmpeg.Transcode-viv.log)

Transcoded segment in VLC
![image](https://github.com/user-attachments/assets/a9c18661-88da-4bf9-8947-014995410466)
Non-transcoded in VLC
![image](https://github.com/user-attachments/assets/14197348-b6af-4bf2-9607-4df7a8a417b2)

**Comment by 1hitsong** [comment]
> Excluding the green screen issue above as fluke, not related to VIV, Jellyfin, etc, I did test several avis that have been in my library for years and the trickplay issue exists for them.

I just tested on my machine with an AVI file that is extremely close to the one you posted
![image](https://github.com/user-attachments/assets/0f409c3f-3b03-4752-940b-a4ecc13e1dbf)

Trickplay worked without issue for me.

If you play your item in the web player, do you get trickplay images?

**Comment by p37307** [comment]
> If you play your item in the web player, do you get trickplay images?

Odd. 
Yes, Trickplay worked in the web player.

Here's another AVI one that won't trickplay in viv, does in viv dev with secret, and does on the web.

![image](https://github.com/user-attachments/assets/8f1317ec-23c8-42d0-9b53-c3aa8625bc6a)

I checked a couple movies I have that are AVIs and they don't, either.

**Comment by 1hitsong** [comment]
Yeah, that's almost identical to the one I was testing with.

Can you clip and share a sample of one of the videos that doesn't show trickplay without the hidden setting?

**Comment by p37307** [comment]
What is the best way to clip without reencoding or changing the file?

**Comment by 1hitsong** [comment]
You can try it using ffmpeg directly: https://superuser.com/questions/377343/cut-part-from-video-file-from-start-position-to-end-position-with-ffmpeg

I recently did the following using the ffmpeg included with Jellyfin to output the first 20 seconds of a video to a separate file. FYI, I'm using terminal in Windows, so you'll need to adjust as needed.

```
cd "C:\Program Files\Jellyfin\Server"

./ffmpeg -i "C:\input.mp4" -c copy -copyts -ss 00:00:00 -to 00:00:20 "C:\output.mp4"
```

**Comment by p37307** [comment]
Sent you a link. I even imported that video into my "junk" library, it created a new item and generated new trickplay. Trickplay failed on viv but did work in viv dev, under normal transcoding.

**Comment by Rand0mB0y** [comment]
> > I've created a hidden setting that allows you to force display the custom trickplay images no matter what. This is a hidden setting because in all my testing this will cause both to show at the same time - one on top of the other.

@1hitsong any chance that a hidden setting to completely disable trickplay on Roku exist? I am trying to test something out

**Comment by 1hitsong** [comment]
There's not. If the server provides them, we use them.

If you ran a dev copy of repo, commenting out [this line](https://github.com/jellyfin/jellyfin-roku/blob/master/components/ItemGrid/LoadVideoContentTask.bs#L106) should be enough to disable them.

**Comment by Rand0mB0y** [comment]
> There's not. If the server provides them, we use them.
> 
> If you ran a dev copy of repo, commenting out [this line](https://github.com/jellyfin/jellyfin-roku/blob/master/components/ItemGrid/LoadVideoContentTask.bs#L106) should be enough to disable them.

I may try this out, thanks very much. And would that stop Roku's own trickplay images when transcoding, too?

Also, do you think that an option to disable trickplay from the settings could be considered in future implementations?
The thing is that it looks like my JF is messing up trickplay generations and db metadata handling of trickplay images. JF-Roku is (obviously) not liking this, and most likely for this reason, I can't seek through transcoded videos via play bar. 
Perhaps other people may find this feature useful to have, too, in similar weird cases?

**Comment by 1hitsong** [comment]
> And would that stop Roku's own trickplay images when transcoding, too?

It would not. That functionality is completely out of our control.

> Also, do you think that an option to disable trickplay from the settings could be considered in future implementations?

Yeah. If it is indeed the source of issues, it would make sense to have an option to disable it.
